SELECT *
FROM ((SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") as OUT_DATE, "출고완료" as "출고여부"
FROM FOOD_ORDER
WHERE DATE_FORMAT(OUT_DATE,'%m-%d') <= '05-01')
UNION
(SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") as OUT_DATE, "출고대기" as "출고여부"
FROM FOOD_ORDER
WHERE DATE_FORMAT(OUT_DATE,'%m-%d') > '05-01')
UNION
(SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE, "%Y-%m-%d") as OUT_DATE, "출고미정" as "출고여부"
FROM FOOD_ORDER
WHERE DATE_FORMAT(OUT_DATE,'%m-%d') is NULL)) as T

ORDER BY ORDER_ID