SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, COUNT(DISTINCT USER_ID) as PUCHASED_USERS, 

ROUND(
COUNT(DISTINCT USER_ID) /(

    SELECT COUNT(USER_ID)
    FROM USER_INFO
    WHERE DATE_FORMAT(joined,'%y') = '21'
), 1) as PUCHASED_RATIO

FROM ONLINE_SALE
WHERE USER_ID IN 
(
    SELECT USER_ID
    FROM USER_INFO
    WHERE DATE_FORMAT(joined,'%y') = '21'
)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE) ASC , MONTH(SALES_DATE) ASC
