SELECT O.PRODUCT_ID, P.PRODUCT_NAME , O.AMOUNT * P.PRICE as TOTAL_SALES

FROM (
    SELECT PRODUCT_ID, sum(AMOUNT) as AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE,'%y-%m') = '22-05'
    GROUP BY PRODUCT_ID
) AS O

JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID

ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC